project:
  type: book
  output-dir: docs

book:
  title: "Environmental Data Literacy"
  license: "CC BY-NC"
  author: 
    - name: Rodney Dyer
      orcid: 0000-0003-4707-3453
      email: rjdyer@vcu.edu
      affiliations: 
      - name: School for Life Sciences and Sustainability
        address: Virginia Commonwealth university
        city: Richmond
        state: VA
        postal-code: 23284
  date: "December 4, 2025"
  chapters:
    - index.qmd
    - syllabus.qmd
    - part: "part1.qmd"
      chapters:
        - narrative_markdown.qmd
        - narrative_datatypes.qmd
        - narrative_containers.qmd
        - narrative_tidyverse.qmd
        - narrative_factors.qmd
        - narrative_joins.qmd
        - narrative_classic.qmd
        - narrative_ggplot.qmd
    - part: "part2.qmd"
      chapters:
        - narrative_points.qmd
        - narrative_vector.qmd
        - narrative_rasters.qmd
    - part: "part3.qmd"
      chapters:
        - narrative_correlation.qmd
        - narrative_regression.qmd
        - narrative_aov.qmd
        - narrative_ordination.qmd

format:
  html:
    css: media/style.css
    theme:
      - cosmo
  pdf:
    documentclass: book
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    papersize: letter
    geometry:
      - margin=1in
    fig-pos: 'H'
    keep-tex: false
