# Index {.unnumbered}

Environmental Data Literacy is a comprehensive guide designed to bridge the gap between ecological research and modern data science. By leveraging the power of the R ecosystem and the Tidyverse, this textbook empowers students and practitioners to move beyond basic spreadsheet analysis into a reproducible workflow encompassing data manipulation, spatial visualization, and advanced statistical modeling. From mastering the fundamentals of Markdown and data structures to executing complex multivariate ordinations and raster processing, this book provides the essential toolkit for turning raw environmental observations into actionable scientific insights.


## License

This book is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](https://creativecommons.org/licenses/by-nc/4.0/).

You are free to:  

  - *Share* — copy and redistribute the material in any medium or format.  
  - *Adapt* — remix, transform, and build upon the material.  

Under the following terms:  

  - *Attribution* — You must give appropriate credit, provide a link to the license, and indicate if changes were made.  
  - *NonCommercial* — You may not use the material for commercial purposes.  


## Logistics

This is a Quarto book created from lecture materials I use to teach [ENVS543: Environmental Data Literacy](https://bulletin.vcu.edu/search/?P=ENVS+543) at [Virginia Commonwealth University](https://vcu.edu).  If you would like to compile this book yourself, you will find the sourse code at its [GitHub repository](https://github.com/DyerlabTeaching/ENVS543-Book).

The following code runs each time you render the project.  It will check to see if you have all the required libraries.  It then installs missing ones and then loads them into memory (so we do not get those stupid package startup messages).

```{r}
source("package_loader.R")

libraries <- extract_libraries_from_markdown()
need_to_install <- check_missing_packages( libraries )
install_missing_packages( need_to_install )
for( pkg in libraries ) { 
  suppressPackageStartupMessages( library(pkg, character.only = TRUE) )
}
ggplot2::theme_set( theme_minimal( base_size=16) )
```








